### ISSUE TITLE
Read permissions from config DB

### ISSUE THREAD

**Issue by pka** [qwc-services/qwc-config-generator#1]
Currently all maps are public.

Should also support a setting analogous to `DEFAULT_ALLOW=false`.

**Comment by mwa** [comment]
Implemented for OGC Service permissions in 385c5b5e and a97f6354

The same OGC permissions are also used for all maps, layers and attributes in the Map Viewer and FeatureInfo Service.

Default permissions or restrictions can be set using the `permissions_default_allow` setting in the generator config file (default: `true`).
