### ISSUE TITLE
Generate thumbnail

### ISSUE THREAD

**Issue by benoitblanc** [qwc-services/qwc-config-generator#20]
Hello,

I started working on a [TODO](https://github.com/qwc-services/qwc-config-generator/blob/11b416a3aa669be2220006b96d6d9b191cc4470c/config_generator/map_viewer_config.py#L422) task in qwc-config-generator service. I would like to generate thumbnails for projets which don't have one in qwc2 assets directory.

I think I have to use [`getThumbnail`](https://github.com/qgis/qwc2/blob/78cae84d861a25d489432928c8c02866861946b8/scripts/themesConfig.py#L59) function in [`themesConfig.py`](https://github.com/qgis/qwc2/blob/master/scripts/themesConfig.py) script from QWC2 repo to generate image from `GetMap` request but I don't know if I am right or not so I would like to have your opinions and advices.

For now, I created some functions from this script in `map_viewer_config.py` to be able to run `GetMap` request.

Next week, I'll try to make a [WIP] pull request here so that you can follow what I am doing.

Thanks,

Benoît

**Comment by manisandro** [comment]
Tracking in #21
