### ISSUE TITLE
allow configuration of timeout of GetProjectSettings call

### ISSUE THREAD

**Issue by manisandro** [qwc-services/qwc-config-generator#25]
Originally reported for qwc-config-service here [1].

The timeout for the GetProjectSettings call is hardcoded to 60 seconds here [2]. For complex projects, this is not long enough. Please allow the configuration of this timeout parameter.

[1] https://github.com/qwc-services/qwc-config-service/issues/3
[2] https://github.com/qwc-services/qwc-config-generator/blob/master/config_generator/capabilities_reader.py#L257

**Comment by demtotal** [comment]
Hello,
 
I'm facing this time out issue, is it now possible to change the parameter ? I tried to change the code file capabilities_reader.py and mount it as a volume but i get errors when doing that . Any alternative solutions ?

Thanks in advance.
Have a nice day.

**Comment by manisandro** [comment]
Done in https://github.com/qwc-services/qwc-config-generator/commit/a3c038367b926240ba86f7e67c06e43b96525fe5

**Comment by demtotal** [comment]
Great news thanks a lot!
