### ISSUE TITLE
Confg generation fails when using virtual fields in a layer

### ISSUE THREAD

**Issue by bladnor** [qwc-services/qwc-config-generator#31]
When configuring virtual fields in a layer then config generation gives a warning. Later, when the layer is edited upon commit a programming error is thrown. See screenshot. Please exclude virtual fields during configuration and editing.

![error-with-virtual-fields](https://user-images.githubusercontent.com/10213881/113869588-2e7ece80-97b1-11eb-85e6-dc6b353a999b.png)

**Comment by manisandro** [comment]
I believe this is since fixed.
