### ISSUE TITLE
Set tiled of sublayer in theme

### ISSUE THREAD

**Issue by vvmruder** [qwc-services/qwc-config-generator#36]
I can set the `tiled` setting on the level of a theme in the tenantConfig.json. Thats fine. Since my theme contains a layer with tricky labels where I do not need the tiling on this specific layer I want to turn it of for this one but keep it enabled for all the other layers.

I played around now for a while but was not able to get it working.

Is there a possibility to do it? And if => How?

Cheers
C

**Comment by manisandro** [comment]
This is currently not possible. The client would need to be extended to split tiled from non-tiled sublayers and send separate requests.

**Comment by vvmruder** [comment]
Thank you for explanation. :+1:
