### ISSUE TITLE
Missing configuration settings

### ISSUE THREAD

**Issue by pka** [qwc-services/qwc-config-generator#4]
- sich gegenseitig ausschliessende Layer lassen sich momentan wieder gemeinsam anzeigen
- massstabsabhängige Sichtbarkeit wird nicht übernommen und entsprechend auch nicht das   Ausgrauen der entsprechenden Layer im Layer-Tree
- geometrielose Layer sind wieder sichtbar
- minSearchScale aus der themesConfig wird nicht übernommen

**Comment by pka** [comment]
Seems to be fixed with #6 ?

**Comment by HusseinKabbout** [comment]
Yes, this should be fixed.

**Comment by pka** [comment]
So you can close it.

**Comment by pka** [comment]
Das Ausgrauen hat noch nicht funktioniert. Es fehlten auch die Metadaten in den Ebeneninformationen. Beispiel:

```
Attribution:    Stadt X
Schlüsselwörter:        ALKIS
Min. Darstellungsmassstab:      0
Max. Darstellungsmassstab:      1:5000
```

**Comment by HusseinKabbout** [comment]
This issue should be fixed with #12 . @pka  Am i missing something or was that everything?

**Comment by pka** [comment]
Greyed out display of incative layers is fixed as well?

**Comment by pka** [comment]
I can't find `minSearchScale` and `minSearchScaleDenom` (see https://github.com/qwc-services/qwc-config-service/commit/eb6687d83920589d1b77c3a8e60ba3becce1c1c1 and https://github.com/qwc-services/qwc-config-service/commit/0ac3386bfec0022a40a9b9f72709adaa141a3309) in #12

**Comment by HusseinKabbout** [comment]
Thats because the `minSearchScaleDenom` was fixed in #6.

**Comment by HusseinKabbout** [comment]
> Greyed out display of incative layers is fixed as well?

Fixed in the latest PR (#14)
