### ISSUE TITLE
'config_file_dir' missing

### ISSUE THREAD

**Issue by danceb** [qwc-services/qwc-config-generator#50]
With the current qwc-config-generator:v2023.05.03 I am getting the following error while generating the config files:
```
QWC ConfigGenerator
Traceback (most recent call last):
  File "/srv/qwc_service/config_generator_cli.py", line 60, in <module>
    generator = ConfigGenerator(config, logger)
TypeError: __init__() missing 1 required positional argument: 'config_file_dir'
```
I think it is in relation with 26845bf. Is there anything new to take into account? My `tenantConfig.json` is placed within `config-in/tenant/default` as before.

**Comment by manisandro** [comment]
Thanks for the report, fixed in v2023.05.09.

**Comment by danceb** [comment]
Thanks, but I think it should be 

`generator = ConfigGenerator(config, logger, os.path.dirname(args.config_file))`

not 

`generator = ConfigGenerator(config, logger, os.path.dirname(config_file))` 

in https://github.com/qwc-services/qwc-config-generator/blob/e729333618a4e712789e7bdb4c4bfe1f7053a5b2/config_generator_cli.py#LL60C74-L60C74

**Comment by manisandro** [comment]
Indeed, I've tagged v2023.05.09.1
