### ISSUE TITLE
 Layers joined via <vectorjoins> in <maplayer> element of QGS project are not supported

### ISSUE THREAD

**Issue by w0pr** [qwc-services/qwc-config-generator#54]
Layerconfiguration in QGIS:
![image](https://github.com/qwc-services/qwc-config-generator/assets/8257055/fbd2d24e-fe80-4531-9759-c9915763383e)

Project consist of two layers, one containing geometry, the other additional attributes from a view residing in another database on another postgresql server with an [oracle_fdw](https://laurenz.github.io/oracle_fdw/) (Oracle foreign data wrapper) extension, which the view relies on to access Oracle view. This server is spun up in a separate container to avoid re-building qwc-postgis image with extension. This service connection is added to pg_service.conf and pf_service-write.conf on server.

This is just by way of explanation, problem also exists when joining layers (tables) from same database service connection in the same schema, since the joined columns are looked up in wrong table.

This will result in [__query_column_metadata(](https://github.com/qwc-services/qwc-config-generator/blob/master/config_generator/qgs_reader.py#L513)) trying to lookup column metadata in the wrong table (of the current layer, not the joined one), which will then break editing & attribute table tools since [data type of column cannot be determined](https://github.com/qwc-services/qwc-config-generator/blob/bef8dbed4399149fd5434d4bc715bcc87045d327/config_generator/qgs_reader.py#L555).
I haven't checked whether attribute table, editing forms or data-service support this or if it's sufficient to either implement this for qwc-config-generator or hand-craft a dataConfig.json and/or other config without relying on qwc-config-generator. 
Please advise.

**Comment by manisandro** [comment]
The easiest way would be if you could debug and propose a PR, as you already have the test setup up and running.

**Comment by manisandro** [comment]
Support for joins has since been implemented in https://github.com/qwc-services/qwc-config-generator/commit/3dccf03170ebae86b100487c8572693451fe28bf
