### ISSUE TITLE
Please check same naming of layers and layer groups

### ISSUE THREAD

**Issue by tpo** [qwc-services/qwc-config-generator#58]
We have now encountered the second instance of a customer naming groups and layers the same, which is not supported.

The customer is only seeing that the map is "not working" and we have to help him debug the issue.

Please add a check to config generator that verifies and enforces that no group and layer are named the same and throws an error otherwise. It needs to be ensured that qgiscloud-api returns the error to the user.

Thanks a lot!

**Comment by manisandro** [comment]
Fixed in https://github.com/qwc-services/qwc-config-generator/commit/b02fdf4b6ea970d396cf39a64c1c8c5e487aa1f9

**Comment by tpo** [comment]
Thanks a lot @manisandro ! Cc: @HusseinKabbout !
