### ISSUE TITLE
defaultSearchProvider in tenantConfig.json is oberwritten by empty searchProvider parameter within theme configuration

### ISSUE THREAD

**Issue by danceb** [qwc-services/qwc-config-generator#61]
Tested with the current version v2023.11.22.

Within the config generation there is the following issue:

- the search providers are specified as default within the `"defaultSearchProviders"` parameter
- within the configuration for a specific theme I have dropped the `"searchProvider"` parameter, as the default configuration should be used
- however the config generator sets `"searchProviders": [],` within each theme configuration, which overrides the default values, so no search provider is available

This works correctly in a comparable case with the background layers. Defining theme within `"defaultBackgroundLayers"` and skipping `"backgroundLayers"` within each theme config results in the right behavior, as there is no `"backgroundLayers": []` added to the mapViewerConfig.json

**Comment by manisandro** [comment]
Thanks, fixed in https://github.com/qwc-services/qwc-config-generator/commit/9df10b502f28a5d0d56e9296487dcd2abae23aad (will tag later today with some other changes)
